//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receiver
    {
        public Receiver()
        {
            this.Consumptions = new HashSet<Consumption>();
        }
    
        public int Id { get; set; }

        public string FirmTitle { get; set; }

        public string CompanyCode { get; set; }

        public string Address { get; set; }

        public string Telephone { get; set; }

        public string Account { get; set; }

        public string ContactPerson { get; set; }
    
        public virtual ICollection<Consumption> Consumptions { get; set; }
    }
}
