//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scrap
    {
        public Scrap()
        {
            this.Arraivings = new HashSet<Arraiving>();
            this.Consumptions = new HashSet<Consumption>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int MetalCode { get; set; }
        public double Amount { get; set; }
        public int Density { get; set; }
        public string Description { get; set; }
        public Nullable<int> Store_Id { get; set; }
    
        public virtual ICollection<Arraiving> Arraivings { get; set; }
        public virtual ICollection<Consumption> Consumptions { get; set; }
        public virtual Store Store { get; set; }
    }
}
