//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Arraivings = new HashSet<Arraiving>();
            this.Consumptions = new HashSet<Consumption>();
            this.Scraps = new HashSet<Scrap>();
        }
    
        public int Id { get; set; }

        public string Title { get; set; }

        public string Responsible { get; set; }

    
        public virtual ICollection<Arraiving> Arraivings { get; set; }

        public virtual ICollection<Consumption> Consumptions { get; set; }

        public virtual ICollection<Scrap> Scraps { get; set; }
    }
}
